CALENDAR_API_HOST: localhost
CALENDAR_API_PORT: 8091
CALENDAR_API_DEBUG_PORT: 8092
CALENDAR_API_LOG_LEVEL: info
CALENDAR_API_DATABASE_ADDR: localhost:5432
CALENDAR_API_DATABASE_DB_NAME: calendar-api-db
CALENDAR_API_DATABASE_USER: calendar-api-user
CALENDAR_API_DATABASE_PASSWORD:  calendar-api-password