CALENDAR_API_HOST:
CALENDAR_API_PORT:
CALENDAR_API_DEBUG_PORT:
CALENDAR_API_LOG_LEVEL:
CALENDAR_API_DATABASE_ADDR:
CALENDAR_API_DATABASE_DB_NAME:
CALENDAR_API_DATABASE_USER:
CALENDAR_API_DATABASE_PASSWORD: